# Generated by Django 5.0.6 on 2024-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.CharField(default='employee', max_length=100),
        ),
        migrations.AddField(
            model_name='newuser',
            name='city',
            field=models.CharField(default='employee', max_length=100),
        ),
        migrations.AddField(
            model_name='newuser',
            name='clinic_name',
            field=models.CharField(default='employee', max_length=100),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone_no',
            field=models.CharField(default='employee', max_length=100),
        ),
    ]
