# Generated by Django 5.0.6 on 2024-06-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_address_newuser_city_newuser_clinic_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='clinic_name',
        ),
    ]
