# Generated by Django 5.0.6 on 2024-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(default='patient', max_length=100),
        ),
    ]
