# Generated by Django 5.0.6 on 2024-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_available_timings_newuser_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='added_by',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
