# Generated by Django 5.0.6 on 2024-06-22 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_appointments_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='slot',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AppointmentTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_timing', models.CharField(default='', max_length=300)),
                ('appo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
