# Generated by Django 5.0.6 on 2024-06-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_appointments_slot_appointmenttimings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimings',
            name='appo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointments'),
        ),
    ]
