# Generated by Django 5.0.6 on 2024-06-22 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_appointmenttimings_appo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(default='', max_length=600)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('appo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointments')),
            ],
        ),
    ]
