# Generated by Django 5.0.6 on 2024-06-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_prescription'),
        ('users', '0012_alter_rating_doctor_alter_rating_patient'),
    ]

    operations = [
    ]
