# Generated by Django 5.0.6 on 2024-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_appointments_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='slot_timing',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='slot',
            field=models.BooleanField(default=False),
        ),
    ]
