# Generated by Django 5.0.6 on 2024-06-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20240622_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
