# Generated by Django 5.0.6 on 2024-06-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_appointments_slot_timing_alter_appointments_slot'),
        ('users', '0015_rating'),
    ]

    operations = [
    ]
